### ISSUE TITLE
fails on first file

### ISSUE THREAD

**Issue by dcsan** [paulcpederson/sass2stylus#2]
I'm trying to convert a folder of files over. when i run one by one things are ok but run in batch i get a fail as below. 

if i move the file and try with next one, same error so it seems a problem with running multiple files more than any specific file.

```

ionic-sass> sass2stylus stylesheets/*.scss stylus        
/Users/dc/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir': File exists - /Users/dc/dev/ref/ionic-sass/stylesheets/_animations.scss (Errno::EEXIST)
	from /Users/dc/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
	from /Users/dc/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'

....

ionic-sass> mkdir temp        
ionic-sass> mv stylesheets/_animations.scss temp 
ionic-sass> sass2stylus stylesheets/* stylus     
/Users/dc/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/fileutils.rb:245:in `mkdir': File exists - /Users/dc/dev/ref/ionic-sass/stylesheets/_action-sheet.scss (Errno::EEXIST)
	from /Users/dc/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/fileutils.rb:245:in `fu_mkdir'
	from /Users/dc/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/fileutils.rb:219:in `block (2 levels) in mkdir_p'
	from /Users/dc/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/fileutils.rb:217:in `reverse_each'
	from /Users/dc/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/fileutils.rb:217:in `block in mkdir_p'
	from /Users/dc/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/fileutils.rb:203:in `each'
	from /Users/dc/.rvm/rubies/ruby-2.0.0-p451/lib/ruby/2.0.0/fileutils.rb:203:in `mkdir_p'
	from /Users/dc/.rvm/gems/ruby-2.0.0-p451/gems/sass2stylus-0.0.1/lib/sass2stylus.rb:11:in `write_file'
	from /Users/dc/.rvm/gems/ruby-2.0.0-p451/gems/sass2stylus-0.0.1/lib/sass2stylus.rb:31:in `s2s'
	from /Users/dc/.rvm/gems/ruby-2.0.0-p451/gems/sass2stylus-0.0.1/lib/sass2stylus.rb:49:in `block in batch'
	from /Users/dc/.rvm/gems/ruby-2.0.0-p451/gems/sass2stylus-0.0.1/lib/sass2stylus.rb:48:in `each'
	from /Users/dc/.rvm/gems/ruby-2.0.0-p451/gems/sass2stylus-0.0.1/lib/sass2stylus.rb:48:in `batch'
	from /Users/dc/.rvm/gems/ruby-2.0.0-p451/gems/sass2stylus-0.0.1/bin/sass2stylus:12:in `<top (required)>'
	from /Users/dc/.rvm/gems/ruby-2.0.0-p451/bin/sass2stylus:23:in `load'
	from /Users/dc/.rvm/gems/ruby-2.0.0-p451/bin/sass2stylus:23:in `<main>'
	from /Users/dc/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in `eval'
	from /Users/dc/.rvm/gems/ruby-2.0.0-p451/bin/ruby_executable_hooks:15:in `<main>'


ionic-sass> sass2stylus stylesheets/_action-sheet.scss stylus      
ionic-sass> sass2stylus stylesheets/_animations.scss stylus      
ionic-sass> sass2stylus stylesheets/_backdrop.scss stylus 
ionic-sass> sass2stylus stylesheets/_badge.scss stylus      

```

**Comment by paulcpederson** [comment]
Hmmm this is definitely a bug. I'll try to look into it.

**Comment by jhogendorn** [comment]
I found this also, using zsh.

It's because ARGV is an array of all the matched files because the shell matches them, but the script is expecting to receive the pattern instead. You can circumvent it by quoting your paths, but the fix is really for alter bin/sass2stylus and the batch functionality to work correctly in this instance.

**Comment by paulcpederson** [comment]
ok, thanks @jhogendorn

**Comment by paulcpederson** [comment]
@dcsan OK, I think I got his working. Try 0.0.2? Feel free to reopen if not resolved.
